blog/articles/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from werkzeug.exceptions import NotFound
from sqlalchemy.orm import joinedload

from blog.extensions import db
from blog.forms.article import CreateArticleForm
from blog.models import Article, Author, Tag

article = Blueprint('article', __name__, url_prefix='/articles', static_folder='../static')


# Контроллер списка статей
@article.route('/', methods=['GET'])
def article_list():
    articles: Article = Article.query.all()
    return render_template(
        'articles/list.html',
        articles=articles,
    )


# Контроллер детальной страницы статьи
@article.route('/<int:article_id>/', methods=['GET'])
def article_detail(article_id):
    _article: Article = Article.query.filter_by(id=article_id).options(joinedload(Article.tags)).one_or_none()
    if _article is None:
        raise NotFound
    return render_template(
        'articles/details.html',
        article=_article,
    )


# Контроллер формы статьи
@article.route('/create/', methods=['GET'])
@login_required
def create_article_form():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    return render_template('articles/create.html', form=form)


# Контроллер создания статьи
@article.route('/', methods=['POST'])
@login_required
def create_article():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]

    if form.validate_on_submit():
        _article = Article(title=form.title.data.strip(), text=form.text.data)

        if current_user.author:
            _article.author_id = current_user.author.id
        else:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
            _article.author_id = author.id

        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                _article.tags.append(tag)

        db.session.add(_article)
        db.session.commit()

        return redirect(url_for('article.article_detail', article_id=_article.id))

    return render_template('articles/create.html', form=form)

blog/author/views.py
from flask import Blueprint, render_template

from blog.models import Author

author = Blueprint('author', __name__, url_prefix='/author', static_folder='../static')


# Контроллер списка авторов
@author.route('/')
def author_list():
    authors = Author.query.all()
    return render_template('authors/list.html', authors=authors)

blog/home/views.py
from flask import Blueprint, render_template

# Объект блюпринта (эксиз) пользователя
home = Blueprint('home', __name__, url_prefix='/', static_folder='../static')


# Регистрация роута внутри блюпринта
@home.route('/')
def home_page():
    return render_template('home.html')

blog/user/views.py
from urllib import request

from werkzeug.exceptions import NotFound
from werkzeug.security import generate_password_hash
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user, login_user


from blog.extensions import db
from blog.forms.user import UserForm
from blog.models import User

# Объект блюпринта (эксиз) пользователя
user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@user.route('register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('user.profile', pk=current_user.id))

    form = UserForm(request.form)
    errors = []
    if request.method == 'POST' and form.validate_on_submit():
        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append('Такая почта уже зарегистрирована')
            return render_template('users/register.html', form=form)

        _user = User(
            email=form.email.data,
            name=form.name.data,
            surname=form.surname.data,
            password=generate_password_hash(form.password.data),
        )

        db.session.add(_user)
        db.session.commit()

        login_user(_user)

    return render_template('users/register.html', form=form, errors=errors,)



# Регистрация роута внутри блюпринта
@user.route('/')
def user_list():
    from blog.models import User
    users = User.query.all()
    return render_template('users/list.html', users=users)


@user.route('/<int:pk>')
def get_user(pk: int):
    from blog.models import User

    _user = User.query.filter_by(id=pk).one_or_none()
    if not _user:
        raise NotFound(f'Пользователь с id{pk} не существует')
    return render_template('users/details.html', user=_user)


@user.route('/<int:pk>')
@login_required
def profile(pk: int):
    from blog.models import User

    _user = User.query.filter_by(id=pk).one_or_none()
    if not _user:
        raise NotFound(f'Пользователь с id{pk} не существует')
    return render_template('users/profile.html', user=_user)

blog/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %}{% endblock %} </title>
    {% include 'menu.html' %}
    <title>Главная</title>
    {% block css %}
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    {% endblock %}
</head>
<body>
<div class="container">
    {% block body %}{% endblock %}
</div>
{% block js %}
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
{% endblock %}
</body>
</html>

blog/templates/home.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block css %}
    <title>Блогеры</title>
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    {% endblock %}
    <title> {% block title %}{% endblock %} </title>
</head>
<body>
{% include 'menu.html' %}
<div class="container">
    {% block body %}{% endblock %}
</div>

{% block js %}
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
{% endblock %}
</body>
</html>

<div id="carouselExampleCaptions" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{ url_for('static', filename='images/1.jpg') }}" class="c-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Кофе Двойной Русский</h5>
        <p>Вы его никак не добьетесь специально, надсадно не добьетесь</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{{ url_for('static', filename='images/2.jpg') }}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Кофе Кейхель</h5>
        <p>Когда магия проходит прямо насквозь тебя и заставляет дрожать сердце</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{{ url_for('static', filename='images/3.jpg') }}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Кофе Романтическая Кузница</h5>
        <p>Кофе, коньяк и мужчины вообще должны быть крепкими</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Предыдущий</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Следующий</span>
  </button>
</div>

blog/templates/menu.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <img src="{{ url_for('static', filename='images/logo2.png') }}" alt="Лого" width="50" height="50">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Переключатель навигации">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Кафе Конфэ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.user_list') }}">Пользователи</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('author.author_list') }}">Авторы</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('article.article_list') }}">Статьи</a>
        </li>
        {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('article.create_article_form') }}">Создать статью</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{{ url_for('auth.logout') }}">Logout ({{ current_user.name }})</a>
            </li>
        {% else %}
            <li class="nav-item">
              <a class="nav-link active" href="{{ url_for('auth.login') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('user.register') }}">Зарегистрироваться</a>
            </li>
        {% endif %}
    </div>
  </div>
</nav>